[workspace]
resolver = "2"

members = [
    "rust/helloworld",
    "rust/memtest",
    "rust/exception",
    "rust/display",
    "rust/fs/shell",
    "rust/net/echoserver",
    "rust/net/httpclient",
    "rust/net/httpserver",
    "rust/net/udpserver",
    "rust/net/bwbench",
    "rust/task/parallel",
    "rust/task/sleep",
    "rust/task/yield",
    "rust/task/priority",
    "rust/task/tls",
    "rust/task/irq",
    "rust/task/affinity",
    "rust/task/wait_queue",
]
exclude = [".arceos"]

[workspace.dependencies]
axstd = { git = "https://github.com/arceos-org/arceos.git" }

[patch.crates-io]
axcpu ={ git = "https://github.com/luodeb/axcpu.git" }
axplat = { git = "https://github.com/luodeb/axplat_crates.git", rev = "2b648a3350987ee9ca615613ae30f430eb412bb7" }
axplat-x86-pc = { git = "https://github.com/luodeb/axplat_crates.git", rev = "2b648a3350987ee9ca615613ae30f430eb412bb7" }
axplat-arm-qemu-virt = { git = "https://github.com/luodeb/axplat_crates.git", rev = "2b648a3350987ee9ca615613ae30f430eb412bb7" }