[package]
name = "arceos-sleep"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axstd = { workspace = true, features = ["multitask", "irq"], optional = true }
axhal_plat_impl = { workspace = true, optional = true }
