name: Test CI

on: [push, pull_request]

env:
  qemu-version: 9.2.1

jobs:
  app-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64, riscv64, aarch64, loongarch64]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: rust-src
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-binutils
    - uses: ./.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - name: Run app tests
      run: |
        ./scripts/get_deps.sh
        make disk_img
        make test ARCH=${{ matrix.arch }}
